export const AUTHENTICATION_PENDING = "AUTH/AUTHENTICATION_PENDING";
export const AUTHENTICATION_SUCCESS = "AUTH/AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTH/AUTHENTICATION_FAILURE";
export const LOGGED_OUT = "AUTH/LOGGED_OUT";
